//----------------------------------------------------------------------------
// N O L D U S   I N F O R M A T I O N   T E C H N O L O G Y   B . V .
//----------------------------------------------------------------------------
// Project    :   Common
// Module     :   Interface
// File       :   IlImage.idl
//----------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
import "IdtIlTypesInterface.idl";
import "IdtTypesInterface.idl";


//----------------------------------------------------------------------------
// struct INCIlImage
//----------------------------------------------------------------------------
// Description: image interface. An image is a memory buffer containing pixel 
//              data. Pixel color and size is determined by 'EIdtIlImageType'
// Note       : 'local' attribute due to direct use of buffer pointer
//----------------------------------------------------------------------------
[
    object,
    local,
    uuid(72AC31FE-4186-47B1-838A-5DBF635DB22A),
    helpstring("INCIlImage"),
    pointer_default(unique)
]
interface INCIlImage : IUnknown
{
    HRESULT GetImageType    ([out] EIdtIlImageType* pType);
    HRESULT GetWidth        ([out] long* pWidth);
    HRESULT GetHeight       ([out] long* pHeight);
    
    HRESULT GetBuffer       ([out] long* pSize,  long* pStepSize, byte** ppBuffer);  // MIDL2279 doesn't allow for const byte**
}
