//----------------------------------------------------------------------------
// N O L D U S   I N F O R M A T I O N   T E C H N O L O G Y   B . V .
//----------------------------------------------------------------------------
// Project    :   N-Linx
// Module     :   Public Entities Contracts
// File       :   StreamingSubscription.thrift
//----------------------------------------------------------------------------
// Revisions  :
//----------------------------------------------------------------------------

include "..\\Types\\CommonTypes.thrift"

namespace * Noldus.NLinx.Contracts.Public.Entities

/** Provides properties about a subscription to a video service for streaming audio/video.*/
struct StreamingSubscription
{
    /** A number that is used by the video service to identify a subscription. This number is generated by the video service and
    /*  is used to keep track of the number of subscriptions. A subscriber should use this number when he unsubscribes from the streaming.*/
    1: required i32 Id,

    /** A list of URL's specifying the available RTSP streaming sources to which you can connect.*/
    2: optional list<string> urls,
}
