//----------------------------------------------------------------------------
// N O L D U S   I N F O R M A T I O N   T E C H N O L O G Y   B . V .
//----------------------------------------------------------------------------
// Project    :   N-Linx
// Module     :   Public Entities Contracts
// File       :   StreamingTicket.thrift
//----------------------------------------------------------------------------
// Revisions  :
// 06-01-2019 Tijmen van Voorthuijsen   - Original version
//----------------------------------------------------------------------------

include "..\\Types\\CommonTypes.thrift"
include "StreamingOptions.thrift"

namespace * Noldus.NLinx.Contracts.Public.Entities

/** A token that belongs to a query that has been submitted to a streaming service. The client who submits a query, should
/*  store this token and use the token later to release or abort the submitted query.*/
struct StreamingTicket
{
    /** A number that is used by the streaming service to identify a running streaming query. This number is generated by a streaming service and is
    /*  unique within the service. This number is in general not unique across services, so not globally unique.*/
    1: required CommonTypes.GUID Id,

    /** The same streaming options as were passed on in the streaming request call. When receiving data back, this field can be used to identify to which request the data belongs.*/
    2: optional StreamingOptions.StreamingOptions streamingOptions
}
